# Generated by Django 5.0.1 on 2024-02-01 18:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("kyrciapp", "0003_followedsummoner_rank_followedsummoner_tier"),
    ]

    operations = [
        migrations.RenameField(
            model_name="followedsummoner",
            old_name="rank",
            new_name="flex_rank_info",
        ),
        migrations.RenameField(
            model_name="followedsummoner",
            old_name="tier",
            new_name="solo_rank_info",
        ),
    ]
